######################################################################
# Automatically generated by qmake (3.0) Sat Aug 24 19:26:44 2013
######################################################################

TEMPLATE = app
TARGET = breeder
INCLUDEPATH += .
QT += xml

# Input
HEADERS += MutableSprite.h MutableSpriteBundle.h QStringEx.h \
    ImageWrapper.h
SOURCES += main.cpp MutableSprite.cpp MutableSpriteBundle.cpp \
    ImageWrapper.cpp

QMAKE_CXXFLAGS += -std=gnu++11
